export const TeamUserData = [
    {
        id: 1,
        name: '강신범',
        team: 'LuckySeven',
        role: 'FE Leader',
        description: '많은 것들을 시도하여 더 나은 개발자가 되겠습니다.',
        image: 'https://github.com/kangsinbeom.png',
        github: 'https://github.com/kangsinbeom',
        mail: 'kangsinbeom@gmail.com',
    },
    {
        id: 2,
        name: '박창민',
        team: 'LuckySeven',
        role: 'BE Leader',
        description: '함께하는 팀원들에게 도움이 되는 일원이 되겠습니다.',
        image: 'https://github.com/ChangMinPark2.png',
        github: 'https://github.com/ChangMinPark2',
        mail: '98qkrckdals@naver.com',
    },
    {
        id: 3,
        name: '하승진',
        team: 'LuckySeven',
        role: 'FE',
        description: '사용자 경험의 발전에 이바지 하고싶은 개발자입니다.',
        image: 'https://github.com/j2an777.png',
        github: 'https://github.com/j2an777',
        mail: 'ha991104@gmail.com',
    },
    {
        id: 4,
        name: '이지수',
        team: 'LuckySeven',
        role: 'BE',
        description: '새로운 것에 망설임 없이 배우고, 즐기는 개발자입니다.',
        image: 'https://github.com/leedidoo.png',
        github: 'https://github.com/leedidoo',
        mail: 'dlwltn6604@skuniv.ac.kr',
    },
    {
        id: 5,
        name: '김수현',
        team: 'LuckySeven',
        role: 'FE',
        description: '체계적인 설계를 둔 목표에 전진하는 사람입니다.',
        image: 'https://github.com/gamjatan9.png',
        github: 'https://github.com/gamjatan9',
        mail: 'soo000307@gmail.com',
    },
    {
        id: 6,
        name: '강솔문',
        team: 'LuckySeven',
        role: 'BE',
        description: '한 번 시작하면 끝을 모르는 도전자입니다.',
        image: 'https://github.com/solmoonkang.png',
        github: 'https://github.com/solmoonkang',
        mail: 'https://ssolv.tistory.com',
    },
    {
        id: 7,
        name: '심예은',
        team: 'LuckySeven',
        role: 'BE',
        description: '어디에서라도 1인 분 이상은 담당합니다.',
        image: 'https://github.com/hesener.png',
        github: 'https://github.com/hesener',
        mail: 'ner.hesed@gmail.com',
    },
]